export const sections = [
  {
    id: 'origin',
    headline: 'This started at the Port Moody City Hall',
    accentWord: 'Port Moody City Hall',
    body: "At 10 years old, I put on my best (only) suit and asked my mom to drive me to city hall so I could speak at a community hearing about the proposed Evergreen Line. It took two more decades, but the line was eventually built.",
    pullQuote: "I choose to believe these events are related.",
    bg: 'bg-gray-950',
  },
  {
    id: 'why-spare',
    headline: 'Transit + Product is the sweet spot',
    accentWord: 'sweet spot',
    body: "I studied Human Geography at UBC with the goal of becoming a planner. Life took a surprise turn to tech. After stints at Hootsuite and Baremetrics, I spent the last 7+ years building an AI-powered video creator for Enterprises at Lumen5.",
    timeline: [
      { label: 'UBC', sub: 'Human Geography' },
      { label: 'Hootsuite', sub: 'Social media' },
      { label: 'Baremetrics', sub: 'SaaS Analytics' },
      { label: 'Lumen5', sub: 'AI video, 7+ yrs' },
      { label: 'Spare', sub: "What's next?", highlight: true },
    ],
    bg: 'bg-gray-900',
  },
  {
    id: 'track-record',
    headline: 'I ship things that move metrics',
    accentWord: 'metrics',
    stats: [
      { value: '40%', numericValue: 40, suffix: '%', iconName: 'DollarSign', label: 'increase in paid purchases after leading a transition to AI-powered voiceover videos' },
      { value: '30%', numericValue: 30, suffix: '%', iconName: 'Clapperboard', label: 'reduction in video creation time from AI-powered script generation' },
      { value: '25%', numericValue: 25, suffix: '%', iconName: 'Rocket', label: 'lift in activation thanks to undo/redo, faster rendering, and targeted onboarding' },
    ],
    bg: 'bg-gray-950',
  },
  {
    id: 'enterprise',
    headline: 'I led the pivot to Enterprise',
    accentWord: 'Enterprise',
    body: "When the self-serve market got crowded, I led the product side of Lumen5's transition to Enterprise. We grew to 100+ enterprise customers and saw consistent 20\u201340% YoY revenue growth over five years.",
    logos: [
      { name: 'KPMG' },
      { name: 'Siemens', src: 'https://cdn.simpleicons.org/siemens/ffffff' },
      { name: 'PwC' },
      { name: 'Deloitte' },
      { name: 'Accenture', src: 'https://cdn.simpleicons.org/accenture/ffffff' },
      { name: 'SAP', src: 'https://cdn.simpleicons.org/sap/ffffff' },
      { name: 'Cisco', src: 'https://cdn.simpleicons.org/cisco/ffffff' },
      { name: 'Swiss Re' },
      { name: 'Best Western' },
      { name: 'Mitsubishi' },
      { name: 'Baker Hughes' },
    ],
    bg: 'bg-gray-900',
  },
  {
    id: 'advocate',
    headline: "I love talking about great products",
    accentWord: 'great products',
    body: "In earlier years at Lumen5, I owned product marketing end-to-end — coordinating and building out materials for our launches. I would happily be an enthusiastic, credible advocate for Spare, both with transit agencies and the broader product community.",
    youtube: 'https://www.youtube.com/embed/d9VSYecC5YM',
    bg: 'bg-gray-950',
  },
  {
    id: 'approach',
    headline: 'My daily toolkit',
    accentWord: 'toolkit',
    body: "I'm not an engineer, but I speak the language well enough to be useful. At Lumen5, I led roadmap planning across four product teams, managed relationships with vendors like ElevenLabs and Shutterstock, and PM'd my own product team at the same time.",
    techLogos: true,
    bg: 'bg-gray-900',
  },
  {
    id: 'contact',
    headline: "Let's talk",
    body: "I'm open to both the Staff and Senior PM roles. Domain fit and being a strong contributor matters more to me than title.",
    links: [
      { label: 'Email me', url: 'mailto:hello@mindthegap.fyi', primary: true, icon: 'email' },
      { label: 'LinkedIn', url: 'https://www.linkedin.com/in/kaegandonnelly', icon: 'linkedin' },
      { label: 'Resume & Cover Letter', url: 'https://canva.link/9smwv33yz6e02au', icon: 'resume' },
    ],
    bg: 'bg-gray-950',
  },
]
